// #pragma once
#ifndef _PARAMETROS_H
#define _PARAMETROS_H

#define ALPHA1 3
#define ALPHA2 3
#define TEMPO_MAX 14*1000

#define TEMPO_REF 50
#define TEMPO_REF_MS TEMPO_REF*1000

#define TEMPO_MODELO_REF 30
#define TEMPO_MODELO_REF_MS TEMPO_MODELO_REF*1000

#define TEMPO_CONTROLE 30
#define TEMPO_CONTROLE_MS TEMPO_CONTROLE*1000

#define TEMPO_LINEARIZACAO 20
#define TEMPO_LINEARIZACAO_MS TEMPO_LINEARIZACAO*1000

#define TEMPO_ROBO 10
#define TEMPO_ROBO_MS TEMPO_ROBO*1000

//const double R = 0.3;

#endif
